### ISSUE TITLE
Mqtt verbindung

### ISSUE THREAD

**Issue by Lordcybertracker** [matthias-bs/Bresser_Weather_Sensor_CC1101_MQTT#4]
Hallo,
Ich hab mich jetzt erst mal an dieser Variante Probiert.
Benutzt wird ein Heltec Wirless Stick lite
Leider scheitere ich am MQTT:
`
07:02:53.624 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
07:02:53.624 -> mode:DIO, clock div:1
07:02:53.624 -> load:0x3fff0030,len:1284
07:02:53.624 -> load:0x40078000,len:12836
07:02:53.669 -> load:0x40080400,len:3032
07:02:53.669 -> entry 0x400805e4
07:02:53.986 -> 
07:02:53.986 -> 
07:02:53.986 -> BresserWeatherSensorMQTT 20221024
07:02:53.986 -> 
07:02:53.986 -> Attempting to connect to SSID: FRITZ!Box 7530 MP...connected!
07:02:57.110 -> Setting time using SNTP .....done!
07:02:59.606 -> Current time: Sun Jan 22 06:02:58 2023
07:02:59.606 -> 
07:02:59.606 -> Checking wifi...
07:02:59.606 -> MQTT connecting... ................
`

MQTT Daten sind alle richtig drin. HAB ja etwa 20 Geräte da drin:
`#ifndef SECRETS
    const char ssid[] = "FRITZ!Box 7530 MP";
    const char pass[] = "xxxxxxxxxxxxxxxxxxxxxxxxxxx";

    #define HOSTNAME "ESP-Bresser"
    #define APPEND_CHIP_ID

    #define    MQTT_PORT     1881 // checked by pre-processor!
    const char MQTT_HOST[] = "192.168.178.6";
    const char MQTT_USER[] = "mqtt"; // leave blank if no credentials used
    const char MQTT_PASS[] = "1234"; // leave blank if no credentials used`
    
Hab extra die Arduino IDE neu aufgesetzt also alles Jungfräulich und die Libs neu reingeladen.
Danke

**Comment by matthias-bs** [comment]
Ist das ein ESP32?

Versuche mal folgendes zu ändern:
```
//#include <WiFiClientSecure.h>
```

```
//#define CHECK_FINGERPRINT
```
```
// Generate WiFi network instance
#if defined(ESP32)
    //WiFiClientSecure net;
    WiFiClient net;
#elif defined(ESP8266)
    BearSSL::WiFiClientSecure net;
#endif
```

```
#if (!defined(CHECK_PUB_KEY) and !defined(CHECK_CA_ROOT) and !defined(CHECK_FINGERPRINT))
        //net.setInsecure();
    #endif
```

Damit sollte eine ungesicherte MQTT-Verbindung zu Stande kommen.

**Comment by matthias-bs** [comment]
Das Projekt wird von mir nicht mehr gewartet oder unterstützt. Stattdessen sollte besser [BresserWeatherSensorReceiver](https://github.com/matthias-bs/BresserWeatherSensorReceiver) genutzt werden.

**Comment by matthias-bs** [comment]
Zum Debugging kann man für den ESP32 in der Arduino IDE unter "Werkzeuge"/"Core Debug Level" auf "Debug" einstellen und bekommt evtl. ein paar hilfreiche Infos.

**Comment by Lordcybertracker** [comment]
Danke Mqtt läuft.
